"""Build-time only. Downloads OFL fonts as .woff2 into assets/fonts/ and
generates shared/fonts.css. Never runs in the shipped extension."""
import re, os, urllib.request, pathlib

ROOT = pathlib.Path(r"C:\Users\DELL\Desktop\coding\Lawha")
FONTDIR = ROOT / "assets" / "fonts"
FONTDIR.mkdir(parents=True, exist_ok=True)

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

# family query, css font-family name, output slug, weights, allowed subsets
FAMILIES = [
    ("Tajawal", "Tajawal", "tajawal", [500, 700], {"arabic", "latin", "latin-ext"}),
    ("IBM+Plex+Sans+Arabic", "IBM Plex Sans Arabic", "plex-arabic",
     [300, 400, 500, 600], {"arabic", "latin", "latin-ext"}),
    ("IBM+Plex+Mono", "IBM Plex Mono", "plex-mono", [400], {"latin", "latin-ext"}),
]

BLOCK = re.compile(
    r"/\*\s*([a-z0-9\-\[\]]+)\s*\*/\s*@font-face\s*\{(.*?)\}", re.S)


def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


faces = []
for query, family, slug, weights, subsets in FAMILIES:
    for weight in weights:
        css = get(f"https://fonts.googleapis.com/css2?family={query}:wght@{weight}"
                  "&display=swap").decode("utf-8")
        for subset, body in BLOCK.findall(css):
            if subset not in subsets:
                continue
            src = re.search(r"url\((https://[^)]+\.woff2)\)", body)
            rng = re.search(r"unicode-range:\s*([^;]+);", body)
            if not src:
                continue
            fname = f"{slug}-{weight}-{subset}.woff2"
            data = get(src.group(1))
            (FONTDIR / fname).write_bytes(data)
            faces.append({
                "family": family, "weight": weight, "file": fname,
                "range": rng.group(1).strip() if rng else None,
                "kb": round(len(data) / 1024, 1),
            })
            print(f"  {fname:44s} {len(data)/1024:6.1f} KB")

lines = [
    "/* Lawha — bundled font faces.",
    "   Generated by tools/fetch-fonts.py. Fonts are OFL-licensed and shipped",
    "   inside the extension: nothing here touches the network at runtime.",
    "   Split by unicode-range so a Latin-only page never decodes Arabic glyphs. */",
    "",
]
for f in faces:
    lines += [
        "@font-face {",
        f"  font-family: '{f['family']}';",
        f"  src: url('../assets/fonts/{f['file']}') format('woff2');",
        f"  font-weight: {f['weight']};",
        "  font-style: normal;",
        "  font-display: swap;",
    ]
    if f["range"]:
        lines.append(f"  unicode-range: {f['range']};")
    lines += ["}", ""]

lines += [
    ":root {",
    "  --font-display: 'Tajawal', system-ui, sans-serif;",
    "  --font-body:    'IBM Plex Sans Arabic', system-ui, sans-serif;",
    "  --font-mono:    'IBM Plex Mono', ui-monospace, monospace;",
    "}",
    "",
]

(ROOT / "shared").mkdir(parents=True, exist_ok=True)
(ROOT / "shared" / "fonts.css").write_text("\n".join(lines), encoding="utf-8")
total = sum(f["kb"] for f in faces)
print(f"\n{len(faces)} faces, {total:.1f} KB total -> shared/fonts.css")
